window.STATE =
{
  "slug": "skill-convert-slice",
  "dir": "2026-09-14-skill-convert-slice",
  "title": "Решения §5 + узкий срез конвертера Claude Code → Antigravity",
  "mode": "semi",
  "depth": "normal",
  "polish": null,
  "tier": "T2",
  "briefFile": "2026-09-14-brief.md",
  "memoryFile": "AGENTS.md",
  "skillDir": "~/.agents/skills/autopilot",
  "startedAt": "2026-09-14T17:11:09+04:00",
  "updatedAt": "2026-09-14T23:10:00+04:00",
  "finishedAt": "2026-09-14T23:10:00+04:00",
  "stages": [
    { "id": "preflight", "status": "done", "startedAt": "2026-09-14T17:11:09+04:00", "finishedAt": "2026-09-14T17:13:40+04:00" },
    { "id": "manifest",  "status": "done", "startedAt": "2026-09-14T17:13:40+04:00", "finishedAt": "2026-09-14T17:16:30+04:00" },
    { "id": "briefing",  "status": "done", "startedAt": "2026-09-14T17:16:30+04:00", "finishedAt": "2026-09-14T17:34:00+04:00" },
    { "id": "spec",      "status": "done", "startedAt": "2026-09-14T17:34:00+04:00", "finishedAt": "2026-09-14T17:58:00+04:00" },
    { "id": "plan",      "status": "done", "startedAt": "2026-09-14T17:58:00+04:00", "finishedAt": "2026-09-14T18:06:00+04:00" },
    { "id": "build",     "status": "done", "startedAt": "2026-09-14T18:06:00+04:00", "finishedAt": "2026-09-14T20:45:00+04:00" },
    { "id": "review",    "status": "done", "startedAt": "2026-09-14T18:22:00+04:00", "finishedAt": "2026-09-14T20:45:00+04:00" },
    { "id": "final",     "status": "done", "startedAt": "2026-09-14T20:45:00+04:00", "finishedAt": "2026-09-14T23:10:00+04:00" }
  ],
  "requirements": {
    "total": 22, "done": 18, "inTicket": 0, "inSpec": 0,
    "placeholder": 0, "deferred": 4, "dropped": 0
  },
  "tickets": [
    { "id": "01", "startedAt": "2026-09-14T18:10:00+04:00", "title": "Три решения §5 в PRD и ADR", "requirements": ["R02","R03","R17i","R20i"],
      "blockedBy": [], "wave": 1, "zone": ["docs/"], "status": "done", "finishedAt": "2026-09-14T19:00:00+04:00", "tests": "make check -> 80 passed", "commit": "1ed8e96",
      "retries": 0, "repairs": 0, "handoffs": 0 },
    { "id": "02", "startedAt": "2026-09-14T18:10:00+04:00", "title": "Способность запретить — отдельная запись описания", "requirements": ["R06","G01"],
      "blockedBy": [], "wave": 1, "zone": ["specs/","src/agent_skill_adapter/envspec/"], "status": "done", "finishedAt": "2026-09-14T18:47:00+04:00", "tests": "make check -> 80 passed (было 79)", "commit": "336a8e7",
      "retries": 0, "repairs": 0, "handoffs": 0 },
    { "id": "03", "startedAt": "2026-09-14T18:48:00+04:00", "title": "Команда convert: чтение, оценка, отчёт, код возврата",
      "requirements": ["R04","R05","R07","R08","R09","R11","R18i","R20i"],
      "blockedBy": ["02"], "wave": 2, "zone": ["src/agent_skill_adapter/convert.py","src/agent_skill_adapter/cli/"], "status": "done", "finishedAt": "2026-09-14T19:30:00+04:00", "tests": "make check -> 94 passed (было 80)", "commit": "ec26d99",
      "retries": 0, "repairs": 0, "handoffs": 0 },
    { "id": "04", "startedAt": "2026-09-14T19:32:00+04:00", "title": "Сборка в раскладку Antigravity и прогон на настоящем скилле",
      "requirements": ["R01","R06","R10","R12","R19i","G02"],
      "blockedBy": ["03"], "wave": 3, "zone": ["src/agent_skill_adapter/convert.py","docs/"], "status": "done", "finishedAt": "2026-09-14T20:45:00+04:00", "tests": "make check -> 102 passed (было 94)", "commit": "aaf7613",
      "retries": 0, "repairs": 1, "handoffs": 0 },
    { "id": "05", "startedAt": "2026-09-14T21:05:00+04:00", "title": "Отчёт называет пропущенное, отказ не спорит с вердиктом",
      "requirements": ["R08","R09.1","R11","R11.1"],
      "blockedBy": ["04"], "wave": 4, "zone": ["src/agent_skill_adapter/convert.py","src/agent_skill_adapter/cli/"], "status": "done", "finishedAt": "2026-09-14T22:10:00+04:00", "tests": "make check -> 115 passed (было 102)", "commit": "4c63332",
      "retries": 0, "repairs": 1, "handoffs": 0 },
    { "id": "06", "startedAt": "2026-09-14T22:12:00+04:00", "title": "Тексты говорят правду, тесты умеют падать",
      "requirements": ["R03","R17i"],
      "blockedBy": ["05"], "wave": 5, "zone": ["docs/","specs/","src/agent_skill_adapter/envspec/","src/agent_skill_adapter/convert.py","tests/unit/"], "status": "done", "finishedAt": "2026-09-14T23:05:00+04:00", "tests": "make check -> 115 passed", "commit": "3181308",
      "retries": 0, "repairs": 1, "handoffs": 0 }
  ],
  "singlePass": null,
  "tests": "make check -> 115 passed (было 79 на старте прогона); make pre-commit-run -> 15 хуков Passed",
  "debt": { "placeholders": [], "assumptions": [], "emptyEnv": [] },
  "additions": [],
  "coverage": { "findings": 10, "missing": 4, "halfCovered": 4, "unparentedAdditions": 0, "actedOn": "все 8 расхождений закрыты правкой спецификации: субагенты, раскладка пользовательского уровня, отношение Gemini/Antigravity, три обхода текстом, формат отчёта, имя итога запуска, убран `blocked` без производителя, целевой файл hooks" },
  "concerns": [
    { "from": "02", "axis": "spec", "where": "specs/anthropic/claude-code-2.1.yaml:340,465",
      "what": "hook.event.UserPromptExpansion и hook.event.PreModelSwitch по-прежнему сами утверждают запрет («can block the expansion», «can block the switch») — то же двойное утверждение в одной записи, которое таск снял для PreToolUse",
      "condition": "либо заметка hook.decision.block называет только вызов инструмента, либо заметки этих двух событий перестают утверждать запрет сами" },
    { "from": "02", "axis": "craft", "where": "specs/anthropic/claude-code-2.1.yaml:495",
      "what": "один hook.decision.block отвечает за два разных запрета — вызов инструмента и раскрытие команды",
      "condition": "запись описания отвечает ровно за одно утверждение" },
    { "from": "02", "axis": "craft", "where": "specs/google/antigravity-2.0.yaml:620",
      "what": "note утверждает про раздел Supported Events, а source_id указывает только на Configuration",
      "condition": "утверждение записи опирается на тот раздел, который она цитирует" },
    { "from": "02", "axis": "craft", "where": "src/agent_skill_adapter/envspec/model.py:77",
      "what": "один довод пересказан четырьмя текстами: docstring модели, комментарии в обоих YAML, docstring теста",
      "condition": "у довода один владелец, остальные ссылаются" },
    { "from": "02", "axis": "craft", "where": "tests/unit/test_envspec_gaps.py:96",
      "what": "новое в тесте только то, что Literal принимает hook-decision — значение константы, которое AGENTS.md §7 запрещает пинить тестом",
      "condition": "тест умеет упасть на поведении, которое не держит ни один другой тест" },
    { "from": "01", "axis": "craft", "where": "docs/adr/0007-hooks-split-in-the-environment-description.md:10, PRD:95",
      "what": "фраза «before a tool call executes; can block it» подана как цитата документации Claude Code, но это текст нашей собственной note, и после таска 02 её нет уже нигде в репозитории",
      "condition": "цитата находится там, куда отсылает: в закреплённом разделе документации или в записи описания" },
    { "from": "01", "axis": "craft", "where": "docs/prd/PRD-001-agent-skill-adapter.md:50",
      "what": "заголовок §5 «Решения, отложенные до готовности описаний сред» теперь накрывает §5.1–5.3, где решения приняты",
      "condition": "заголовок раздела описывает всё его содержимое" },
    { "from": "01", "axis": "craft", "where": "docs/prd/PRD-001-agent-skill-adapter.md:99, ADR-0007:29",
      "what": "список обходов для непереносимого hook выписан целиком и с теми же обоснованиями в двух документах",
      "condition": "у одного списка одно место, второе ссылается" },
    { "from": "01", "axis": "manifest", "where": "docs/prd/PRD-001-agent-skill-adapter.md:52",
      "what": "шапка §5 называет снятой тройку «словарь / обращение с исходом неизвестно / hooks и субагенты», но строки про «неизвестно» в списке отложенных никогда не было, а вычеркнутая строка про субагентов в тройке не названа",
      "condition": "перечисление в шапке называет те же три строки, которые вычеркнуты ниже" },
    { "from": "01", "axis": "spec", "where": "docs/prd/PRD-001-agent-skill-adapter.md:71-73",
      "what": "фраза «§5 вводит ровно одно новое имя» стоит вплотную над абзацем, который вводит второй термин — origin",
      "condition": "абзац про origin назван переиспользованием существующего Origin, как это сделано для Outcome" },
    { "from": "03", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:285",
      "what": "советы-обходы выбираются по gap.kind, поэтому hook-событие, которого нет в описаниях, получает lossy и ноль строк advice",
      "condition": "перечень обходов следует из того, что найдено в папке скилла, а не из того, объявила ли пара описаний нужную запись" },
    { "from": "03", "axis": "craft", "where": "src/agent_skill_adapter/cli/main.py:43",
      "what": "критерий «в stdout только JSON, --report уводит его в файл» не проверяет ни один тест",
      "condition": "требование, живущее вне шва convert, имеет свою проверку на своём шве" },
    { "from": "03", "axis": "craft", "where": "src/agent_skill_adapter/cli/main.py:73",
      "what": "--report в несуществующую папку даёт FileNotFoundError трассировкой, минуя отчёт и код возврата",
      "condition": "отказ CLI выходит сообщением и кодом, а не трассировкой" },
    { "from": "03", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:191",
      "what": "три отказа разбора не покрыты случаем: файл без ведущего ---, frontmatter не-отображением, не-UTF-8",
      "condition": "каждая ветка отказа на границе доверия имеет свой случай" },
    { "from": "03", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:266",
      "what": "при двух объявленных событиях hook.decision.block попадает в отчёт один раз с found_as первого — потерянный запрет читается как относящийся только к нему",
      "condition": "строка отчёта называет все места, из-за которых появилась, либо не называет ни одного" },
    { "from": "03", "axis": "craft", "where": "tests/unit/test_convert.py:284",
      "what": "assert пиннит формулировку совета, что AGENTS.md §7 запрещает",
      "condition": "утверждается состав (три совета, по одному на обход), а не слово внутри прозы" },
    { "from": "03", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:78",
      "what": "довод про разделение записи переписан шестой раз (model.py, два YAML, ADR-0007, PRD §5.3, docstring BLOCK)",
      "condition": "у довода одно место, остальные ссылаются" },
    { "from": "03", "axis": "spec", "where": "tests/unit/test_convert.py",
      "what": "критерий «в stdout только JSON, --report уводит его в файл» не закреплён тестом; ревьюер проверил руками",
      "condition": "либо один тест через CliRunner, либо критерий вычёркивается как покрытый правилом одного шва" },
    { "from": "03", "axis": "manifest", "where": "specs/gaps/claude-code-to-antigravity.md:78",
      "what": "отказ дают 4 записи из 77, и среди них skill.dir.references — обычная часть скилла",
      "condition": "закрыто пользователем 2026-09-14: отказ оставлен сознательно, починка — правило перевода FR-6" },
    { "from": "04", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:455",
      "what": "shutil.copytree/copy2 идут по символическим ссылкам, поэтому подпапка-ссылка утаскивает в результат содержимое того, на что указывает — прогон 2 в документе шёл через ~/.claude/skills/autopilot, который сам ссылка",
      "condition": "собранный скилл состоит из того, что лежит в папке скилла: либо symlinks=True, либо ссылка названа в отчёте" },
    { "from": "04", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:397",
      "what": "папка, которой в описании цели нет места, пропускается через continue, и в отчёте это видно только отсутствием строки в written",
      "condition": "пропуск — названный факт, потому что «не собрали, некуда» и «не дошли руки» из отсутствия неразличимы" },
    { "from": "04", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:270",
      "what": "папка .omc даёт id skill.dir..omc с двойной точкой, и это уехало в committed-документ прогона",
      "condition": "правило построения id даёт читаемый id для имени, начинающегося с точки" },
    { "from": "04-repair", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:487",
      "what": "отказ по выходу за out уходит с кодом 3 и затирает вердикт таблицы, хотя это такое же «не смогли записать», как столкновение, которому та же починка вердикт сохраняет",
      "condition": "одинаковые по природе отказы обращаются с вердиктом одинаково" },
    { "from": "04-repair", "axis": "craft", "where": "src/agent_skill_adapter/convert.py:670",
      "what": "вердикт восстанавливается обратным поиском по EXIT_CODE.items() — молча держится на уникальности кодов",
      "condition": "сопоставление «код отказа → вердикт» — явное отображение, а не обратный проход" },
    { "from": "04-repair", "axis": "craft", "where": "tests/unit/test_convert.py:412",
      "what": "тест на путь за пределами out утверждает exit_code != 0 и пройдёт при 6, 8 и любом будущем коде",
      "condition": "тест на отказ называет код, которым отказ выходит" },
    { "from": "06", "axis": "craft", "where": "src/agent_skill_adapter/cli/main.py:107",
      "what": "правило старшинства кодов («11 только поверх 0 и 1») живёт веткой в CLI, тогда как сами коды и их смыслы — в convert.py; второй вызывающий обязан повторить ветку у себя",
      "condition": "решение, какой код побеждает, стоит рядом с кодами — чтобы правило нельзя было забыть, а не только вспомнить" },
    { "from": "06", "axis": "craft", "where": "src/agent_skill_adapter/convert.py (id папок)",
      "what": "критерий про читаемый id снят разменом: lstrip('.') приравнивал .scripts/ к scripts/ — падение без отчёта либо тихий переезд скрытой папки. skill.dir..omc с двойной точкой остался",
      "condition": "снято сознательно; чинится записью точки в id, а не отбрасыванием" }
  ],
  "reviewers": { "manifestSpec": "rev-manifest-spec", "craft": "rev-craft" },
  "blind": {
    "ran": "2026-09-14T20:50:00+04:00",
    "launched": true,
    "commands": "make install; make check (102 passed); convert на трёх настоящих скиллах — коды 0, 1, 3; три прогона совпали дословно с docs/converting-a-real-skill.md; в ~/.gemini и .agents ничего не записано",
    "drift": [
      { "requirement": "R08 (FR-15)", "manifest": "done", "blind": "частично",
        "what": "якоря и алиасы YAML принимаются молча и дают exit 0; предела на размер и глубину заголовка нет",
        "action": "доделывает таск 05" },
      { "requirement": "R08 (FR-16)", "manifest": "done", "blind": "частично",
        "what": "SKILL.md без description даёт exit 0 «clean», хотя оба описания помечают поле Required",
        "action": "доделывает таск 05" }
    ],
    "alsoFound": [
      { "what": "--specs по умолчанию относительный: запуск не из корня репозитория даёт exit 3 с тем же кодом, что настоящий отказ по unknown",
        "action": "доделывает таск 05" },
      { "what": "символическая ссылка из папки скилла разыменовывается и содержимое копируется внутрь результата — это FR-14, отложенный брифом",
        "action": "в отчёт" },
      { "what": "в отчёте абсолютные пути машины — это FR-29, отложенный брифом",
        "action": "в отчёт" },
      { "what": "hooks.json кладётся в корень --out, а не в <out>/.agents/hooks.json; отчёт объясняет, что запись staged and not merged",
        "action": "в отчёт, сделано сознательно (FR-40)" }
    ]
  }
}
